version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - dependabot
    commit-message:
      prefix: chore
