######################## default configuration ####################
baseURL = "https://absolutearray.com/"
copyright = "Pedro Torres"
DefaultContentLanguage  = "en"
disableLanguages        = []
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
languageCode = "en-us"
licence = "MIT"
licenselink = "https://raw.githubusercontent.com/Corfucinas/blog/master/LICENCE"
title = "In a quest for vast knowledge"
theme = "liva-hugo"
summaryLength = "10"
paginate = 6
disqusShortname = ""
hasCJKLanguage = true
pluralizeListTitles = false
disableHugoGeneratorInject = true

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"


############################## navigation ###############################
[menu]

  # main menu
  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 1

  [[menu.main]]
  name = "Articles"
  URL = "articles"
  weight = 2

  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 3

  [[menu.main]]
  name = "Resume"
  URL = "./resume/resume.html"
  weight = 4

  # footer menu
  [[menu.footer]]
  name = "About"
  URL = "about"
  weight = 1

  [[menu.footer]]
  name = "Articles"
  URL = "articles"
  weight = 2

  [[menu.footer]]
  name = "Contact"
  URL = "contact"
  weight = 3

  [[menu.footer]]
  name = "Resume"
  URL = "./resume/resume.html"
  weight = 4


#################### default parameters ################################
[params]
logo = "images/favicon/favicon.ico"
home = "Home"
# Meta data
description = "This is meta description"
author = "Pedro Torres"
# Google Analitycs
googleAnalytics = "G-WHSXXMY8EX"
# Contact Information
# mobile = "0124857985320"
# email = "demo@email.com"
location = "Shanghai, China"
# copyright
copyright = "| copyright &copy; 2021 Absolute Array. All Rights Reserved |"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "images/preloader/web-preloader.svg" # use .png , .svg or .gif format

  # search
  [params.search]
  enable = true

############################ news letter ########################
# [params.newsletter]
# enable = true
# title = "Join the newsletter"
# content = ""


# cookies
[params.cookies]
enable = true
expire_days = 2


############################# social site ########################
[[params.social]]
title = "Email"
icon = "ti-email" # themify icon : https://themify.me/themify-icons
link = "mailto:pedro.torres.cruz@gmail.com"

[[params.social]]
title = "Github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/corfucinas"

[[params.social]]
title = "Linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/in/pedro-torres-cruz/"
