baseURL = "https://corfucinas.github.io/"
# Form Spree Contact Form
# contactFormAction = "https://formspree.io/f/your-form-hash-here"
copyright = "Pedro Torres"
DefaultContentLanguage = "en"
description = "Personal website"
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
# Google Site Verify
# googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
hasCJKLanguage = true
indexDateFormat = "Mon, Jan 2, 2006"
languageCode = "en"
licence = "MIT"
licenselink = "https://raw.githubusercontent.com/Corfucinas/blog/master/LICENCE"
listDateFormat = "Jan 2"
# Syntax highlighting
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
singleDateFormat = "Mon, Jan 2, 2006"
summarylength = 10
theme = "anatole"
title = "Pedro Torres | blog"


# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"
# [params]
# gtagId = "G-XXXXXXXXXX"
# ^Checkthis


[build]
  writeStats = true

[params]
  # description = ""
  author = "Pedro Torres"
  # customCss = ["css/homepage.css"]
  # customJs = ["js/profile_picture.js"]
  displayMode = "light"
  doNotLoadAnimations = false
  enableMediumZoom = true
  images = ["images/site-feature-image.png"]
  keywords = ""
  mainSections = ["post"]
  profilePicture = "/images/profile_picture.jpg"
  title = "In a quest to acquire vast knowledge"
  [params.simpleAnalytics]
    # enable = true
    # customurl = "https://analytics.example.com"

  ## Math settings
  [params.math]
    enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
    use = "katex"  # options: "katex", "mathjax". default is "katex".

  ## Social links
  # use 'fab' when brand icons, use 'fas' when standard solid icons.
  [[params.socialIcons]]
    icon = "fab fa-linkedin"
    title = "Linkedin"
    url = "https://www.linkedin.com/in/pedro-torres-cruz/"

  [[params.socialIcons]]
    icon = "fab fa-github"
    title = "GitHub"
    url = "https://github.com/Corfucinas"

  [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "e-mail"
    url = "mailto:pedro.torres.cruz@gmail.com"

## Menu items

[menu]

  [[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 100

  [[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 200

  [[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  weight = 300

  [[menu.main]]
  identifier = "resume"
  name = "Resume"
  url = "./resume/resume.html"
  weight = 400

  [[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 500

## Taxonomies for Opengraph
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
