name: build
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 5'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Update theme
        run: git submodule update --init --recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.6.0
        with:
          hugo-version: 'latest'
          extended: true

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Build website
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.0
        with:
          personal_token: ${{ secrets.HUGO_TOKEN }}
          external_repository: corfucinas/absolute-array
          publish_branch: master
          keep_files: false
          publish_dir: ./public
