name: build
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 5"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2.3.4
        with:
          submodules: true
          fetch-depth: 0

      - name: Update theme
        run: git submodule update --init --recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.5.0
        with:
          hugo-version: "latest"
          extended: true

      - name: Build website
        run: hugo --gc --minify --cleanDestinationDir --verbose

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          personal_token: ${{ secrets.HUGO_TOKEN }}
          external_repository: corfucinas/corfucinas.github.io
          publish_branch: master
          keep_files: true
          publish_dir: ./public
          cname: corfucinas.github.io
