name: review_dog
on:
  push:
    branches:
      - master
jobs:
  review_dog_linter:
    name: runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: reviewdog/action-languagetool@v1.5
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: info
