name: review_dog
on: [pull_request]
jobs:
  review_dog_linter:
    name: runner
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: reviewdog/action-languagetool@v1.4
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: info
